spring.application.name=banking_backend
server.port= 5000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jackson.deserialization.FAIL_ON_NULL_FOR_PRIMITIVES=false

resilience4j.ratelimiter.instances.apiLimiter.limit-for-period=10
resilience4j.ratelimiter.instances.apiLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.apiLimiter.timeout-duration=0