spring.application.name=banking_backend
server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.hikari.maximum-pool-size=5
spring.jackson.deserialization.FAIL_ON_NULL_FOR_PRIMITIVES=false

resilience4j.ratelimiter.instances.apiLimiter.limit-for-period=10
resilience4j.ratelimiter.instances.apiLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.timeout-duration=0